fix for large payloads
aciidb0mb3r/SwiftMQTT pull request #14
Opened 2016-11-10 09:40 UTC by netgfx

Applied a fix to handle payloads more than 32kb

Fixes issue #13

2016-11-16 10:24 UTC, bhargavg requested changes

2016-11-16 10:24 UTC, bhargavg commented on SwiftMQTT/SwiftMQTT/MQTTSessionStreamDelegate.swift
> +                        print("error cannot read mqtt payload")
I think, instead of printing, we should call `self.delegate?.mqttErrorOccurred(in: self)` and let the delegate do the appropriate thing.

2016-11-16 10:24 UTC, bhargavg commented on SwiftMQTT/SwiftMQTT/MQTTSessionStreamDelegate.swift
> +        self.queue.sync {
Sorry, I fail to understand why we need to dispatch the reading logic synchronously to a concurrent queue.

2017-02-15 11:40 UTC, pavithramh commented
Hi,

After including code for larger payloads, app crashes  with "terminating with uncaught exception of type NSException" 


![screen shot 2017-02-15 at 5 09 05 pm](https://cloud.githubusercontent.com/assets/20104114/22972897/a145a56e-f3a1-11e6-8f3f-38f920ac78f8.png)

2024-07-09 08:23 UTC, closed without merging